version: '3.5'

services:
  gorda:
    container_name: workspace
    build:
      context: .
    ports:
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "5005:5005"
      - "9000:9000"
      - "9099:9099"
    volumes:
      - ../:/home/dev/apps/
    tty: true