version: '3.5'

services:
  gorda:
    container_name: workspace
    build:
      context: .
      args:
        - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    ports:
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "5005:5005"
      - "9000:9000"
      - "9099:9099"
      - "9005:9005"
    volumes:
      - ../:/home/node/apps/
    tty: true