version: '3.9'
networks:
  backend:
  frontend:
services:
  gorda:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    container_name: gorda_dock
    build:
      context: .
    networks:
      - frontend
    ports:
      - "6000:6000"
      - "3000:3000"
    volumes:
      - ../:/root/apps
  emulators:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    container_name: emulators
    depends_on:
      - gorda
    build:
      context: ./emulators
    networks:
      - backend
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "5005:5005"
      - "5001:5001"
      - "9000:9000"
      - "9199:9199"
      - "9099:9099"
      - "9005:9005"
      - "8080:8080"
      - "9150:9150"
    volumes:
      - ../:/home/node/firebase
