version: '3.7'
networks:
  local:
    driver: bridge
services:
  gorda:
    build:
      context: .
      args:
        - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    networks:
      - local
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "5000:5000"
      - "5001:5001"
      - "5005:5005"
      - "9000:9000"
      - "9199:9199"
      - "9099:9099"
      - "9005:9005"
    volumes:
      - ../:/home/node/apps/